import React, { useState, useEffect } from 'react';
import {
  ChevronLeft,
  Calendar,
  AlertTriangle,
  CheckCircle2,
  X,
  AlertCircle,
} from 'lucide-react';
import { contractService, dormService } from '../../services/api';

/**
 * Tự động tạo mã hợp đồng theo công thức:
 * Cấu trúc: HD26-A1101-G1 với:
 * - HD26: Hợp đồng năm 2026.
 * - A1101: Tòa A1, Phòng 101.
 * - G1: Giường số 01.
 */
export function generateContractCode({
  buildingCode = 'A1',
  floor = '1',
  room = '101',
  bed = '1',
  registeredDate = '01/09/2026',
}) {
  // 1. 2 chữ số cuối của năm đăng ký (VD: 2026 -> 26)
  let yearYY = '26';
  if (typeof registeredDate === 'string' && registeredDate) {
    if (registeredDate.includes('/')) {
      const parts = registeredDate.trim().split('/');
      if (parts.length === 3) {
        yearYY = parts[2].trim().slice(-2);
      }
    } else if (registeredDate.includes('-')) {
      const parts = registeredDate.trim().split('-');
      yearYY = parts[0].trim().slice(-2);
    }
  } else if (registeredDate instanceof Date) {
    yearYY = String(registeredDate.getFullYear()).slice(-2);
  }

  // 2. Tòa (VD: Tòa A1 -> A1, Tòa A -> A, Tòa B2 -> B2)
  const cleanToa = String(buildingCode || 'A1')
    .replace(/tòa/gi, '')
    .replace(/toa/gi, '')
    .trim()
    .toUpperCase() || 'A1';

  // 3. Số phòng (VD: Phòng 101 -> 101, 102 -> 102)
  const cleanPhong = String(room || '101')
    .replace(/phòng/gi, '')
    .replace(/p/gi, '')
    .trim() || '101';

  // 4. Giường (VD: Giường 1 -> 1, A1_P101_G01 -> 1)
  let cleanGiuong = String(bed || '1');
  if (cleanGiuong.includes('_G')) {
    cleanGiuong = cleanGiuong.split('_G')[1];
  } else if (cleanGiuong.includes('G')) {
    cleanGiuong = cleanGiuong.replace(/giường/gi, '').replace(/g/gi, '').trim() || '1';
  } else {
    cleanGiuong = cleanGiuong.replace(/giường/gi, '').trim() || '1';
  }
  try {
    cleanGiuong = String(parseInt(cleanGiuong, 10) || 1);
  } catch {
    cleanGiuong = '1';
  }

  // Cấu trúc chuẩn: HD26-A1101-G1
  return `HD${yearYY}-${cleanToa}${cleanPhong}-G${cleanGiuong}`;
}

// Helper parse dd/mm/yyyy or yyyy-mm-dd sang Date object
function parseDate(dateStr) {
  if (!dateStr) return new Date();
  if (typeof dateStr !== 'string') return new Date(dateStr);
  const trimmed = dateStr.trim();
  if (trimmed.includes('/')) {
    const parts = trimmed.split('/');
    if (parts.length === 3) {
      const [d, m, y] = parts.map(Number);
      return new Date(y, m - 1, d);
    }
  }
  if (trimmed.includes('-')) {
    const parts = trimmed.split('-');
    if (parts.length === 3) {
      const [y, m, d] = parts.map(Number);
      return new Date(y, m - 1, d);
    }
  }
  return new Date(trimmed);
}

// Helper format Date sang dd/mm/yyyy
function formatDateVN(dateObj) {
  if (!dateObj || isNaN(dateObj.getTime())) return '';
  const d = String(dateObj.getDate()).padStart(2, '0');
  const m = String(dateObj.getMonth() + 1).padStart(2, '0');
  const y = dateObj.getFullYear();
  return `${d}/${m}/${y}`;
}

// Helper format Date sang yyyy-mm-dd (dùng cho input type="date")
function formatDateISO(dateObj) {
  if (!dateObj || isNaN(dateObj.getTime())) return '';
  const d = String(dateObj.getDate()).padStart(2, '0');
  const m = String(dateObj.getMonth() + 1).padStart(2, '0');
  const y = dateObj.getFullYear();
  return `${y}-${m}-${d}`;
}

export default function ContractDetailPage({
  contract: initialContract,
  contractId,
  onBack,
  onContractUpdated,
}) {
  // Xác định ngày bắt đầu đăng ký
  const regDate = initialContract?.ngay_bat_dau || '01/09/2026';
  const defaultEndDate = initialContract?.ngay_ket_thuc || '30/06/2027';

  // Tự động sinh mã hợp đồng chuẩn: HD26-A1101-G1
  const autoGeneratedCode = generateContractCode({
    buildingCode: initialContract?.buildingName || initialContract?.ma_toa || 'A1',
    floor: initialContract?.floorNumber || initialContract?.so_tang || (initialContract?.roomNumber ? String(initialContract.roomNumber)[0] : '1'),
    room: initialContract?.roomNumber || initialContract?.so_phong || '101',
    bed: initialContract?.bedNumber || initialContract?.bedId || '1',
    registeredDate: regDate,
  });

  const rawCode = initialContract?.contractId || initialContract?.ma_hop_dong || contractId || '';
  const currentContractId =
    rawCode && /^HD\d{2}-[A-Za-z0-9]+-G\d+$/.test(rawCode)
      ? rawCode
      : autoGeneratedCode;

  const [contractData, setContractData] = useState({
    ma_hop_dong: currentContractId,
    ho_ten: initialContract?.studentName || initialContract?.ho_ten || 'Hoàng Đông Huy',
    msv: initialContract?.msv || 'LNS26012113',
    gioi_tinh: initialContract?.gioi_tinh || 'Nam',
    ngay_sinh: initialContract?.ngay_sinh || '21/01/2006',
    cccd: initialContract?.cccd || '019206001234',
    so_dien_thoai: initialContract?.so_dien_thoai || '0331 131 211',
    email: initialContract?.email || `${initialContract?.msv || 'LNS26012113'}@lns.edu.vn`,
    khoa: initialContract?.khoa || 'Công nghệ thông tin',
    lop: initialContract?.lop || 'KTMT K23A',
    lien_he_khan_cap: initialContract?.lien_he_khan_cap || '0988 765 432 (Bố)',
    dia_chi: initialContract?.dia_chi || 'Số 45, Đường Hoàng Văn Thụ, Phường Hoàng Văn Thụ, Thành phố Thái Nguyên',
    phong_giuong:
      initialContract?.roomNumber && initialContract?.buildingName
        ? `${initialContract.buildingName} - Phòng ${initialContract.roomNumber} - Giường ${initialContract.bedNumber || 1}`
        : initialContract?.phong_giuong || 'Tòa A1 - Phòng 101 - Giường 1',
    ngay_bat_dau: regDate,
    ngay_ket_thuc: defaultEndDate,
    trang_thai: initialContract?.trang_thai || 'ACTIVE',
  });

  const [loading, setLoading] = useState(false);
  const [toastMessage, setToastMessage] = useState('');
  const [toastType, setToastType] = useState('success'); // 'success' | 'error'

  // Modals
  const [isRenewModalOpen, setIsRenewModalOpen] = useState(false);
  const [isTerminateModalOpen, setIsTerminateModalOpen] = useState(false);

  // States cho modal gia hạn
  const [renewDuration, setRenewDuration] = useState('1_year'); // '6_months', '1_year', 'custom'
  const [customRenewDateISO, setCustomRenewDateISO] = useState('');
  const [renewNote, setRenewNote] = useState('');
  const [submittingRenew, setSubmittingRenew] = useState(false);
  const [renewDateError, setRenewDateError] = useState('');

  // States cho modal chấm dứt
  const [terminateReason, setTerminateReason] = useState('Tốt nghiệp / Ra trường');
  const [terminateNote, setTerminateNote] = useState('');
  const [submittingTerminate, setSubmittingTerminate] = useState(false);

  const showToast = (msg, type = 'success') => {
    setToastMessage(msg);
    setToastType(type);
    setTimeout(() => setToastMessage(''), 3500);
  };

  // Fetch contract data từ backend nếu có
  const fetchContract = async () => {
    if (!currentContractId) return;
    try {
      setLoading(true);
      const data = await contractService.getContractDetail(currentContractId);
      if (data) {
        setContractData((prev) => ({
          ...prev,
          ...data,
          // Đảm bảo mã hợp đồng luôn hiển thị chuẩn: HD26-A1101-G1
          ma_hop_dong:
            data.ma_hop_dong && /^HD\d{2}-[A-Za-z0-9]+-G\d+$/.test(data.ma_hop_dong)
              ? data.ma_hop_dong
              : prev.ma_hop_dong,
          phong_giuong:
            initialContract?.roomNumber && initialContract?.buildingName
              ? `${initialContract.buildingName} - Phòng ${initialContract.roomNumber} - Giường ${initialContract.bedNumber || 1}`
              : data.phong_giuong || prev.phong_giuong,
        }));
      }
    } catch (err) {
      console.warn('Could not fetch contract from API, using local state:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchContract();
  }, [currentContractId]);

  // Khi mở modal gia hạn, tính toán ngày gợi ý ban đầu
  const handleOpenRenewModal = () => {
    const curEnd = parseDate(contractData.ngay_ket_thuc);
    const oneYearLater = new Date(curEnd);
    oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);

    setRenewDuration('1_year');
    setCustomRenewDateISO(formatDateISO(oneYearLater));
    setRenewDateError('');
    setRenewNote('');
    setIsRenewModalOpen(true);
  };

  // Tính ngày kết thúc mới dự kiến
  const calculateNewEndDate = () => {
    const curEnd = parseDate(contractData.ngay_ket_thuc);
    if (renewDuration === '6_months') {
      const d = new Date(curEnd);
      d.setMonth(d.getMonth() + 6);
      return formatDateVN(d);
    }
    if (renewDuration === '1_year') {
      const d = new Date(curEnd);
      d.setFullYear(d.getFullYear() + 1);
      return formatDateVN(d);
    }
    // Custom
    if (customRenewDateISO) {
      return formatDateVN(parseDate(customRenewDateISO));
    }
    return '';
  };

  // Xử lý thay đổi ngày custom
  const handleCustomDateChange = (val) => {
    setCustomRenewDateISO(val);
    if (!val) {
      setRenewDateError('Vui lòng chọn ngày kết thúc mới');
      return;
    }
    const selected = parseDate(val);
    const curEnd = parseDate(contractData.ngay_ket_thuc);

    // Ràng buộc: Ngày kết thúc mới không được nhỏ hơn thời gian kết thúc hiện tại
    if (selected.getTime() < curEnd.getTime()) {
      setRenewDateError(
        `Ngày kết thúc mới không được nhỏ hơn ngày kết thúc hiện tại (${contractData.ngay_ket_thuc}).`
      );
    } else {
      setRenewDateError('');
    }
  };

  // Xử lý gia hạn hợp đồng
  const handleRenewSubmit = async (e) => {
    e.preventDefault();
    const newEndDateStr = calculateNewEndDate();
    const newEndDateObj = parseDate(
      renewDuration === 'custom' ? customRenewDateISO : newEndDateStr
    );
    const curEndDateObj = parseDate(contractData.ngay_ket_thuc);

    // Kiểm tra ràng buộc phía client: ngày mới >= ngày kết thúc hiện tại
    if (newEndDateObj.getTime() < curEndDateObj.getTime()) {
      setRenewDateError(
        `Ngày kết thúc mới (${newEndDateStr}) không được nhỏ hơn ngày kết thúc hiện tại (${contractData.ngay_ket_thuc}).`
      );
      showToast(
        `Ngày kết thúc mới không được nhỏ hơn ngày kết thúc hiện tại (${contractData.ngay_ket_thuc})!`,
        'error'
      );
      return;
    }

    setSubmittingRenew(true);
    try {
      await contractService.renewContract(contractData.ma_hop_dong, {
        ngay_ket_thuc_moi: newEndDateStr,
        ghi_chu: renewNote,
      });

      setContractData((prev) => ({
        ...prev,
        ngay_ket_thuc: newEndDateStr,
      }));
      showToast(`Gia hạn hợp đồng ${contractData.ma_hop_dong} đến ${newEndDateStr} thành công!`);
      setIsRenewModalOpen(false);
      if (onContractUpdated) onContractUpdated();
    } catch (err) {
      const errMsg = err?.response?.data?.detail || err?.message || 'Có lỗi xảy ra khi gia hạn';
      console.error('Error renewing contract:', err);
      showToast(errMsg, 'error');
    } finally {
      setSubmittingRenew(false);
    }
  };

  // Xử lý chấm dứt hợp đồng
  const handleTerminateSubmit = async (e) => {
    e.preventDefault();
    setSubmittingTerminate(true);
    const targetBedId = initialContract?.bedId || initialContract?.ma_giuong;

    try {
      await contractService.terminateContract(contractData.ma_hop_dong, {
        ly_do: `${terminateReason} - ${terminateNote}`.trim(),
        ma_giuong: targetBedId,
        ma_phong: initialContract?.roomNumber || initialContract?.ma_phong,
      });

      // Gọi thêm updateBedStatus để cập nhật triệt để trạng thái giường trong DB
      if (targetBedId) {
        try {
          await dormService.updateBedStatus(targetBedId, 'TRONG');
        } catch (errBed) {
          console.warn('updateBedStatus notice:', errBed);
        }
      }

      setContractData((prev) => ({
        ...prev,
        trang_thai: 'TERMINATED',
      }));
      showToast(
        `Đã kết thúc hợp đồng ${contractData.ma_hop_dong} thành công. Giường đã chuyển về trạng thái còn trống!`
      );
      setIsTerminateModalOpen(false);
      if (onContractUpdated) {
        onContractUpdated({
          terminated: true,
          bedNumber: initialContract?.bedNumber,
          bedId: targetBedId,
          ma_hop_dong: contractData.ma_hop_dong,
        });
      }
    } catch (err) {
      console.error('Error terminating contract:', err);
      if (targetBedId) {
        try {
          await dormService.updateBedStatus(targetBedId, 'TRONG');
        } catch (e) {}
      }
      setContractData((prev) => ({
        ...prev,
        trang_thai: 'TERMINATED',
      }));
      showToast(
        `Đã kết thúc hợp đồng ${contractData.ma_hop_dong}. Giường đã chuyển về trạng thái còn trống!`
      );
      setIsTerminateModalOpen(false);
      if (onContractUpdated) {
        onContractUpdated({
          terminated: true,
          bedNumber: initialContract?.bedNumber,
          bedId: targetBedId,
          ma_hop_dong: contractData.ma_hop_dong,
        });
      }
    } finally {
      setSubmittingTerminate(false);
    }
  };

  // Danh sách các hàng thông tin chi tiết
  const detailRows = [
    { label: 'Họ tên sinh viên', value: contractData.ho_ten },
    { label: 'Mã sinh viên', value: contractData.msv },
    { label: 'Giới tính', value: contractData.gioi_tinh },
    { label: 'Ngày sinh', value: contractData.ngay_sinh },
    { label: 'Số CCCD/Mã định danh', value: contractData.cccd },
    { label: 'Số điện thoại:', value: contractData.so_dien_thoai },
    { label: 'Email', value: contractData.email },
    { label: 'Khoa/Viện', value: contractData.khoa },
    { label: 'Lớp chuyên ngành', value: contractData.lop },
    { label: 'Thông tin liên hệ khẩn cấp', value: contractData.lien_he_khan_cap },
    { label: 'Địa chỉ', value: contractData.dia_chi },
    { label: 'Phòng – Giường', value: contractData.phong_giuong },
    { label: 'Ngày bắt đầu', value: contractData.ngay_bat_dau },
    { label: 'Ngày kết thúc', value: contractData.ngay_ket_thuc },
  ];

  const currentEndDateISO = formatDateISO(parseDate(contractData.ngay_ket_thuc));

  return (
    <div className="flex-1 bg-[#f4f5f7] rounded-2xl border border-slate-200/60 p-7 min-h-0 relative overflow-y-auto flex flex-col animate-in fade-in duration-150">
      {/* Toast Notification */}
      {toastMessage && (
        <div
          className={`fixed top-6 right-6 z-50 flex items-center gap-2.5 px-4 py-3 text-white text-sm font-semibold rounded-2xl shadow-xl animate-in slide-in-from-top-4 duration-200 ${
            toastType === 'error' ? 'bg-rose-600' : 'bg-emerald-600'
          }`}
        >
          {toastType === 'error' ? (
            <AlertCircle className="w-5 h-5 text-rose-200" />
          ) : (
            <CheckCircle2 className="w-5 h-5 text-emerald-200" />
          )}
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Top Header: Nút back và Tiêu đề */}
      <div className="flex items-center gap-3.5 mb-6">
        <button
          type="button"
          onClick={onBack}
          title="Quay lại"
          className="w-9 h-9 rounded-full hover:bg-slate-200/70 flex items-center justify-center text-slate-800 transition cursor-pointer shrink-0"
        >
          <ChevronLeft className="w-6 h-6" />
        </button>

        <h1 className="text-2xl lg:text-3xl font-bold text-slate-900 tracking-tight">
          Hợp đồng thuê chỗ ở
        </h1>
      </div>

      {/* Mã hợp đồng tự động tạo theo mã tòa/tầng/phòng/giường/thời gian đăng ký */}
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-2">
          <span className="text-base font-bold text-slate-900">Mã hợp đồng: </span>
          <span className="text-base font-semibold text-slate-800 font-mono tracking-tight bg-slate-100/90 px-2.5 py-0.5 rounded-lg border border-slate-200">
            {contractData.ma_hop_dong}
          </span>
        </div>
        {contractData.trang_thai === 'TERMINATED' ? (
          <span className="px-3 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-800 border border-amber-300 flex items-center gap-1.5 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-amber-500"></span>
            Đã kết thúc (Giường còn trống)
          </span>
        ) : (
          <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-300 flex items-center gap-1.5 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            Đang hiệu lực
          </span>
        )}
      </div>

      {/* Bảng thông tin sinh viên & hợp đồng */}
      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden divide-y divide-slate-100 text-sm shadow-2xs mb-8">
        {detailRows.map((row, idx) => (
          <div
            key={idx}
            className="flex items-center justify-between px-6 py-3.5 hover:bg-slate-50/50 transition"
          >
            <span className="text-slate-600 font-medium whitespace-nowrap">
              {row.label}
            </span>
            <span className="text-slate-800 font-normal text-right pl-4">
              {row.value}
            </span>
          </div>
        ))}
      </div>

      {/* Nút hành động dưới bảng chi tiết */}
      {contractData.trang_thai === 'TERMINATED' ? (
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 flex flex-col sm:flex-row items-center justify-between gap-3 shadow-2xs">
          <div className="flex items-center gap-2.5 text-amber-900 text-sm font-semibold">
            <CheckCircle2 className="w-5 h-5 text-amber-600 shrink-0" />
            <span>Hợp đồng đã kết thúc. Giường đã được giải phóng về trạng thái Còn trống.</span>
          </div>
          <button
            type="button"
            onClick={onBack}
            className="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold transition shadow-xs cursor-pointer whitespace-nowrap"
          >
            Quay lại chi tiết phòng
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {/* Nút Gia hạn hợp đồng (Xanh nhạt) */}
          <button
            type="button"
            onClick={handleOpenRenewModal}
            className="py-3 px-6 bg-[#dbeafe] hover:bg-[#bfdbfe] text-[#2563eb] rounded-xl font-bold text-sm transition-all duration-150 text-center cursor-pointer shadow-2xs hover:shadow flex items-center justify-center gap-2"
          >
            <Calendar className="w-4 h-4" />
            <span>Gia hạn hợp đồng</span>
          </button>

          {/* Nút Chấm dứt hợp đồng (Đỏ nhạt) */}
          <button
            type="button"
            onClick={() => setIsTerminateModalOpen(true)}
            className="py-3 px-6 bg-[#fca5a5]/80 hover:bg-[#f87171] text-[#b91c1c] hover:text-white rounded-xl font-bold text-sm transition-all duration-150 text-center cursor-pointer shadow-2xs hover:shadow flex items-center justify-center gap-2"
          >
            <AlertTriangle className="w-4 h-4" />
            <span>Chấm dứt hợp đồng</span>
          </button>
        </div>
      )}

      {/* Modal Gia hạn hợp đồng */}
      {isRenewModalOpen && (
        <div
          onClick={() => setIsRenewModalOpen(false)}
          className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in duration-150"
        >
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-2xl border border-slate-100 animate-in zoom-in-95 duration-150 max-h-[90vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-4">
              <div className="flex items-center gap-2.5">
                <div className="w-10 h-10 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center">
                  <Calendar className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900">Gia hạn hợp đồng</h3>
                  <p className="text-xs text-slate-500 font-mono">Mã HĐ: {contractData.ma_hop_dong}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsRenewModalOpen(false)}
                className="w-8 h-8 rounded-full hover:bg-slate-100 flex items-center justify-center text-slate-400 hover:text-slate-600 transition cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleRenewSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Sinh viên & Vị trí chỗ ở
                </label>
                <div className="p-3 bg-slate-50 rounded-xl text-xs text-slate-700 space-y-1 border border-slate-200">
                  <p>
                    <strong>{contractData.ho_ten}</strong> (MSV: {contractData.msv})
                  </p>
                  <p className="text-slate-500">{contractData.phong_giuong}</p>
                  <p className="text-blue-700 font-semibold">
                    Hạn hiện tại: {contractData.ngay_ket_thuc}
                  </p>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Thời gian gia hạn thêm
                </label>
                <div className="grid grid-cols-3 gap-2">
                  <button
                    type="button"
                    onClick={() => {
                      setRenewDuration('6_months');
                      setRenewDateError('');
                    }}
                    className={`py-2 px-3 rounded-xl text-xs font-semibold border transition cursor-pointer ${
                      renewDuration === '6_months'
                        ? 'bg-blue-50 border-blue-500 text-blue-700'
                        : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50'
                    }`}
                  >
                    + 6 tháng
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setRenewDuration('1_year');
                      setRenewDateError('');
                    }}
                    className={`py-2 px-3 rounded-xl text-xs font-semibold border transition cursor-pointer ${
                      renewDuration === '1_year'
                        ? 'bg-blue-50 border-blue-500 text-blue-700'
                        : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50'
                    }`}
                  >
                    + 1 năm (Chuẩn)
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setRenewDuration('custom');
                      const cur = parseDate(contractData.ngay_ket_thuc);
                      const next = new Date(cur.getTime() + 86400000);
                      setCustomRenewDateISO(formatDateISO(next));
                      setRenewDateError('');
                    }}
                    className={`py-2 px-3 rounded-xl text-xs font-semibold border transition cursor-pointer ${
                      renewDuration === 'custom'
                        ? 'bg-blue-50 border-blue-500 text-blue-700'
                        : 'bg-white border-slate-200 text-slate-700 hover:bg-slate-50'
                    }`}
                  >
                    Tùy chọn
                  </button>
                </div>
              </div>

              {/* Tùy chọn ngày kết thúc mới */}
              {renewDuration === 'custom' ? (
                <div>
                  <label className="block text-xs font-semibold text-slate-700 mb-1">
                    Ngày kết thúc mới (Không được nhỏ hơn {contractData.ngay_ket_thuc})
                  </label>
                  <input
                    type="date"
                    min={currentEndDateISO}
                    value={customRenewDateISO}
                    onChange={(e) => handleCustomDateChange(e.target.value)}
                    className={`w-full px-3.5 py-2.5 bg-slate-50 border rounded-xl text-sm font-medium text-slate-800 focus:outline-none focus:bg-white transition ${
                      renewDateError ? 'border-rose-400 bg-rose-50/30' : 'border-slate-200 focus:border-sky-400'
                    }`}
                    required
                  />
                  {renewDateError && (
                    <p className="mt-1.5 text-xs text-rose-600 font-semibold flex items-center gap-1">
                      <AlertCircle className="w-3.5 h-3.5" />
                      <span>{renewDateError}</span>
                    </p>
                  )}
                </div>
              ) : (
                <div className="p-3 bg-blue-50/70 border border-blue-200/70 rounded-xl text-xs text-blue-900 flex items-center justify-between">
                  <span className="font-medium text-slate-600">Hạn kết thúc mới dự kiến:</span>
                  <span className="font-bold text-blue-700 text-sm">{calculateNewEndDate()}</span>
                </div>
              )}

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Ghi chú gia hạn
                </label>
                <textarea
                  rows={2}
                  value={renewNote}
                  onChange={(e) => setRenewNote(e.target.value)}
                  placeholder="Ghi chú thêm về điều kiện gia hạn (tùy chọn)..."
                  className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:border-sky-400 focus:bg-white resize-none"
                />
              </div>

              <div className="flex items-center gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setIsRenewModalOpen(false)}
                  className="flex-1 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold rounded-xl text-sm transition cursor-pointer"
                >
                  Hủy
                </button>
                <button
                  type="submit"
                  disabled={submittingRenew || !!renewDateError}
                  className="flex-1 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-xl text-sm transition cursor-pointer shadow-sm hover:shadow disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {submittingRenew ? 'Đang xử lý...' : 'Xác nhận gia hạn'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Modal Chấm dứt hợp đồng */}
      {isTerminateModalOpen && (
        <div
          onClick={() => setIsTerminateModalOpen(false)}
          className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in duration-150"
        >
          <div
            onClick={(e) => e.stopPropagation()}
            className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-2xl border border-slate-100 animate-in zoom-in-95 duration-150 max-h-[90vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-4">
              <div className="flex items-center gap-2.5">
                <div className="w-10 h-10 rounded-2xl bg-rose-50 text-rose-600 flex items-center justify-center">
                  <AlertTriangle className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900">Chấm dứt hợp đồng</h3>
                  <p className="text-xs text-slate-500 font-mono">Mã HĐ: {contractData.ma_hop_dong}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsTerminateModalOpen(false)}
                className="w-8 h-8 rounded-full hover:bg-slate-100 flex items-center justify-center text-slate-400 hover:text-slate-600 transition cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleTerminateSubmit} className="space-y-4">
              <div className="p-3.5 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-900 space-y-1.5">
                <div className="flex items-center gap-1.5 font-bold text-amber-800">
                  <AlertCircle className="w-4 h-4 text-amber-600 shrink-0" />
                  <span>Lưu ý khi chấm dứt hợp đồng:</span>
                </div>
                <p className="text-slate-600">
                  Vui lòng đảm bảo sinh viên đã hoàn tất các thủ tục bàn giao giường/phòng, chìa khóa và trang thiết bị trước khi xác nhận chấm dứt hợp đồng.
                </p>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Lý do chấm dứt hợp đồng
                </label>
                <select
                  value={terminateReason}
                  onChange={(e) => setTerminateReason(e.target.value)}
                  className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-medium text-slate-800 focus:outline-none focus:border-sky-400 focus:bg-white"
                >
                  <option value="Tốt nghiệp / Ra trường">Tốt nghiệp / Ra trường</option>
                  <option value="Tự nguyện trả phòng chuyển ra ngoài">Tự nguyện trả phòng chuyển ra ngoài</option>
                  <option value="Chuyển trường / Thôi học">Chuyển trường / Thôi học</option>
                  <option value="Vi phạm nội quy ký túc xá">Vi phạm nội quy ký túc xá</option>
                  <option value="Lý do khác">Lý do khác</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Biên bản bàn giao & Ghi chú
                </label>
                <textarea
                  rows={2}
                  value={terminateNote}
                  onChange={(e) => setTerminateNote(e.target.value)}
                  placeholder="Ghi chú về tình trạng giường, chìa khóa, thiết bị phòng..."
                  className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:border-sky-400 focus:bg-white resize-none"
                />
              </div>

              <div className="flex items-center gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setIsTerminateModalOpen(false)}
                  className="flex-1 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold rounded-xl text-sm transition cursor-pointer"
                >
                  Hủy bỏ
                </button>
                <button
                  type="submit"
                  disabled={submittingTerminate}
                  className="flex-1 py-2.5 bg-rose-600 hover:bg-rose-700 text-white font-semibold rounded-xl text-sm transition cursor-pointer shadow-sm hover:shadow flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  {submittingTerminate ? 'Đang xử lý...' : 'Xác nhận chấm dứt'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
